### ISSUE TITLE
微信版本问题

### ISSUE THREAD

**Issue by HolmesCloud** [zhouxinghua001/Wechat-Emotion-Parser#3]
您好，感谢您的脚本，让喜欢的表情包可以用来做自己的视频素材，不知道您是否能否分享一下教程VERSION_LIST中的各个版本对应的数据参数如何寻找？

**Comment by CN-Grace** [comment]
> 您好，感谢您的脚本，让喜欢的表情包可以用来做自己的视频素材，不知道您是否能否分享一下教程VERSION_LIST中的各个版本对应的数据参数如何寻找？

哎呀太久没更新了，versionlist可以从pywdump的https://raw.githubusercontent.com/xaoyaoo/PyWxDump/refs/heads/master/pywxdump/WX_OFFS.json 
获取

目前该项目将其更名为WX_OFFS.json，但我~~懒得更新~~

**Comment by HolmesCloud** [comment]
好的，非常感谢您的及时回复。
